--引用https://advancewars.fandom.com/wiki/List_of_Units
--以下为对上述资料的个人猜想
Corps={
	{name="Commando",translate="突击队",note="手榴弹,机枪,可游泳过海,对小型舰船有一定伤害"},
	{name="WorkCar",translate="工作车",note="外形像推土机,履带移动,可改变地形(填海造路,愚公移山,开荒种草,砍伐树木等)"},
	{name="Convoy",translate="护航车",note="车辆,视野1,机枪,可搭载1单位步兵系,可过山(相当于牺牲视野,多了搭载步兵系和爬山功能的Recon)"},
	{name="Buggy",translate="越野车",note="车辆,手榴弹,机枪(火力和突击队一样,车辆般的防御力)"},
	{name="Humvee",translate="悍马车",note="车辆,反坦克炮,机枪,防御能力比越野车高点(汽车版AntiTank)"},
	{name="TankDestroyer",translate="坦克歼击车",note="带有机枪和反坦克炮的坦克(坦克版的AntiTank)"},
	{name="IFV(InfantryFightingVehicle)",translate="步兵战车",note="和APC一样的防御,带有反坦克炮和机枪,可过河"},
	{name="TrainCannon",translate="列车炮",note="只能在铁路和工厂中移动,具有2-6的射程和很大的威力(相当于战舰的陆地版),可搭载2单位的陆军"},
	{name="SupplyPlane",translate="补给飞机",note="可称为加油机,只能给翼飞机加油"},
	{name="AegisWarship",translate="宙斯盾战舰",note="带有反舰导弹和对空导弹的战舰(对空对海不对地的战舰)"},
	{name="MercenaryMissileFrigate",translate="佣兵导弹护卫舰",note="带有对城导弹和对空导弹的护卫舰"},
	{name="Tanker(避免误认为坦克应该用OilTanker)",translate="油船",note="给舰船补给燃料弹药的船"},--由于水上有BlackBoat,陆上有APC,感觉作用不大,不如弄成气垫船
	--个人
	{name="MissileBoat",translate="导弹艇",note="带有1发导弹,可对直升机和陆军攻击,其它功能和炮艇一样"},
	{name="HoverCraft",translate="气垫船",note="船厂造,可在水上和陆地上航行,可搭载2单位占领系或1单位车辆系"},
}
