Corps={
	--步兵
	{name="Infantry",chinese="步兵",corpType='LandForce',price=1000,vision=2,
	move={movement=3,moveType="Foot",gasMax=99},
	weapons={
		{name="MachineGun"}},
	capturable=true--[[具有占领能力]]},
	--机械兵
	{name="Mech",chinese="机械兵",corpType='LandForce',price=3000,vision=2,
	move={movement=2,moveType="Boot",gasMax=70},
	weapons={
		{name="RocketTube",ammunitionMax=3},
		{name="MachineGun"}},
	capturable=true--[[具有占领能力]]},
	--装甲车
	{name="APC",chinese="装甲车",corpType='LandForce',price=5000,vision=1,
	move={movement=6,moveType="Tread",gasMax=70},
	suppliable=true,--[[可补给所有部队]]},
	--侦察车
	{name="Recon",chinese="侦察车",corpType='LandForce',price=4000,vision=5,
	move={movement=8,moveType="Tire",gasMax=80},
	weapons={
		{name="MachineGun"}},
	},
	--大炮
	{name="Artillery",chinese="大炮",corpType='LandForce',price=6000,vision=1,
	move={movement=5,moveType="Tread",gasMax=50},
	weapons={
		{name="Cannon",minRange=2,maxRange=3,ammunitionMax=9}}
	},
	--火箭车
	{name="Rockets",chinese="火箭车",corpType='LandForce',price=15000,vision=1,
	move={movement=5,moveType="Tire",gasMax=50},
	weapons={
		{name="Rocket",minRange=3,maxRange=5,ammunitionMax=6}}
	},
	--导弹车
	{name="Missiles",chinese="导弹车",corpType='LandForce',price=12000,vision=5,
	move={movement=4,moveType="Tire",gasMax=50},
	weapons={
		{name="Missile",minRange=3,maxRange=5,ammunitionMax=6}}
	},
	--坦克
	{name="Tank",chinese="坦克",corpType='LandForce',price=7000,vision=3,
	move={movement=6,moveType="Tread",gasMax=70},
	weapons={
		{name="Cannon",ammunitionMax=9},
		{name="MachineGun"}}
	},
	--中型坦克
	{name="MiddleTank",chinese="中型坦克",corpType='LandForce',price=16000,vision=1,
	move={movement=5,moveType="Tread",gasMax=50},
	weapons={
		{name="Cannon",ammunitionMax=8},
		{name="MachineGun"}}
	},
	--防空炮
	{name="AntiAir",chinese="防空炮",corpType='LandForce',price=8000,vision=2,
	move={movement=6,moveType="Tread",gasMax=60},
	weapons={
		{name="Vulcan",ammunitionMax=9}}
	},
	--运输直升机
	{name="TransportCopter",chinese="运输直升机",corpType='AirForce',price=5000,vision=2,
	move={movement=6,moveType="Heli",gasMax=99},
	},
	--武装直升机
	{name="BattleCopter",chinese="武装直升机",corpType='AirForce',price=9000,vision=3,
	move={movement=6,moveType="Heli",gasMax=99},
	weapons={
		{name="Missile",ammunitionMax=6},
		{name="MachineGun"}}
	},
	--战斗机
	{name="Fighter",chinese="战斗机",corpType='AirForce',price=20000,vision=2,
	move={movement=9,moveType="Plane",gasMax=99},
	weapons={
		{name="Missile",ammunitionMax=9}}
	},
	--轰炸机
	{name="Bomber",chinese="轰炸机",corpType='AirForce',price=22000,vision=2,
	move={movement=7,moveType="Plane",gasMax=99},
	weapons={
		{name="Bomb",ammunitionMax=9}}
	},
	--战舰
	{name="BattleShip",chinese="战舰",corpType='NavyForce',price=28000,vision=2,
	move={movement=5,moveType="Ship",gasMax=99},
	weapons={
		{name="Cannon",minRange=2,maxRange=6,ammunitionMax=9}}
	},
	--巡洋舰
	{name="Cruiser",chinese="巡洋舰",corpType='NavyForce',price=18000,vision=3,
	move={movement=6,moveType="Ship",gasMax=99},
	weapons={
		{name="Missile",ammunitionMax=6},
		{name="AntiAirGun"}}
	},
	--潜艇
	{name="Submarine",chinese="潜艇",corpType='NavyForce',price=20000,vision=5,
	move={movement=5,moveType="Ship",gasMax=60},
	weapons={
		{name="Torpedo",ammunitionMax=6}},
	hidable=true--[[可隐藏]]},
	--登录艇
	{name="Lander",chinese="登陆艇",corpType='NavyForce',price=12000,vision=1,
	move={movement=6,moveType="Boat",gasMax=99},
	},
	--新型核能坦克
	{name="NeoTank",chinese="新型坦克",corpType='LandForce',price=22000,vision=1,
	move={movement=6,moveType="Tread",gasMax=99},
	weapons={
		{name="Cannon",ammunitionMax=9},
		{name="MachineGun"}},
	},
	--黑船
	{name="BlackBoat",chinese="黑船",corpType='NavyForce',price=7500,vision=1,
	move={movement=7,moveType="Boat",gasMax=60},
	repairable=true--[[可修复别的单位]]},
	--黑炸弹
	{name="BlackBomb",chinese="黑弹",corpType='AirForce',price=25000,vision=1,
	move={movement=9,moveType="Plane",gasMax=45},
	explodable=true--[[可爆炸]]},
	--巨型坦克
	{name="MegaTank",chinese="巨型坦克",corpType='LandForce',price=28000,vision=1,
	move={movement=4,moveType="Tread",gasMax=50},
	weapons={
		{name="Cannon",ammunitionMax=3},
		{name="MachineGun"}}
	},
	--管道炮
	{name="PipeRunner",chinese="管道炮",corpType='LandForce',price=20000,vision=4,
	move={movement=9,moveType="Pipe",gasMax=50},
	weapons={
		{name="Cannon",minRange=2,maxRange=5,ammunitionMax=9},
		{name="MachineGun"}}
	},
	--航空母舰
	{name="Carrier",chinese="航空母舰",corpType='NavyForce',price=30000,vision=4,
	move={movement=5,moveType="Ship",gasMax=99},
	weapons={
		{name="Missile",ammunitionMax=9}}
	},
	--隐形飞机
	{name="Stealth",chinese="隐形飞机",corpType='AirForce',price=24000,vision=4,
	move={movement=6,moveType="Plane",gasMax=60},
	weapons={
		{name="Missile",ammunitionMax=6}}
	}
}
